name: Deploy Snowpark Apps

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install SnowSQL
        run: curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash
      
      - run: ls
      - run: ls -a ~/
      
      - run: bash snowsql-1.2.24-linux_x86_64.bash
        shell: bash
        env:
          SNOWSQL_DEST: ${{ github.workspace }}
          SNOWSQL_LOGIN_SHELL: ~/.bash_profile
